"use client";

import { useState, useEffect } from "react";
import { 
  ArrowLeft, 
  TrendingUp, 
  ShoppingBag, 
  Users as UsersIcon, 
  DollarSign,
  Loader2,
  Calendar,
  PieChart,
  Printer,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Order } from "@/types";
import { getTodayOrders } from "@/lib/firestore-service";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { useAuth } from "@/context/AuthContext";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import SimpleBackupManager from "@/components/SimpleBackupManager";

export default function DashboardPage() {
  const { user, profile, loading: authLoading } = useAuth();
  const router = useRouter();
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!authLoading && (!user || (profile?.role !== 'super_admin' && profile?.role !== 'admin'))) {
      toast.error("Unauthorized access");
      router.push("/");
    }
  }, [user, profile, authLoading, router]);

  useEffect(() => {
    const loadDashboard = async () => {
      try {
        setLoading(true);
        const todayOrders = await getTodayOrders();
        setOrders(todayOrders);
      } catch (error) {
        toast.error("Failed to load dashboard data");
      } finally {
        setLoading(false);
      }
    };

    if (user) loadDashboard();
  }, [user]);

  const totalSales = orders.reduce((acc, order) => acc + (order.status === 'cancelled' ? 0 : order.total), 0);
  const totalProfit = orders.reduce((acc, order) => acc + (order.status === 'cancelled' ? 0 : (order.profit || 0)), 0);
  const totalOrders = orders.filter(o => o.status !== 'cancelled').length;
  const averageOrderValue = totalOrders > 0 ? totalSales / totalOrders : 0;

  const generateReport = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text("Daily Sales & Profit Report", 105, 20, { align: "center" });
    
    doc.setFontSize(10);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 35);
    doc.text(`Generated By: ${profile?.displayName || user?.email}`, 20, 40);
    
    // Summary Stats
    autoTable(doc, {
      startY: 50,
      head: [['Metric', 'Value']],
      body: [
        ['Total Sales (Gross)', `P${totalSales.toLocaleString()}`],
        ['Total Profit (Net)', `P${totalProfit.toLocaleString()}`],
        ['Total Orders', totalOrders.toString()],
        ['Average Order Value', `P${averageOrderValue.toFixed(2)}`]
      ],
      theme: 'grid',
      headStyles: { fillColor: 'orange' }
    });

    // Category Breakdown
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Category', 'Items Sold']],
      body: Object.entries(categoryCount).map(([cat, count]) => [cat, count.toString()]),
      theme: 'grid',
      headStyles: { fillColor: 'blue' }
    });

    // Recent Transactions
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Order ID', 'Time', 'Total', 'Payment']],
      body: orders.map(order => [
        `#${order.id?.slice(-6).toUpperCase()}`,
        order.createdAt?.toDate().toLocaleTimeString(),
        `P${order.total.toFixed(2)}`,
        order.paymentMethod
      ]),
      theme: 'grid',
      headStyles: { fillColor: 'green' }
    });

    doc.save(`daily-report-${new Date().toISOString().split('T')[0]}.pdf`);
    toast.success("Sales report generated!");
  };

  // Simple category breakdown (based on items in orders)
  const categoryCount: Record<string, number> = {};
  orders.forEach(order => {
    order.items.forEach(item => {
      categoryCount[item.category] = (categoryCount[item.category] || 0) + item.quantity;
    });
  });

  if (authLoading || !user) {
    return (
      <div className="h-screen flex items-center justify-center">
        <Loader2 className="h-10 w-10 animate-spin text-orange-500" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col lg:flex-row">
      {/* Mobile Header */}
      <div className="lg:hidden bg-white border-b px-4 py-4 flex items-center justify-between sticky top-0 z-10 shadow-sm">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={() => router.push("/")} className="h-10 w-10 rounded-xl">
            <ArrowLeft className="h-6 w-6" />
          </Button>
          <h1 className="font-black text-xl text-gray-900 tracking-tighter">Analytics</h1>
        </div>
        <Button 
          variant="outline"
          size="icon"
          className="h-10 w-10 rounded-xl border-indigo-100 text-indigo-600"
          onClick={generateReport}
          disabled={orders.length === 0}
        >
          <Printer className="h-5 w-5" />
        </Button>
      </div>

      <div className="flex-1 max-w-7xl mx-auto w-full p-4 lg:p-8 space-y-6 lg:space-y-8">
        <div className="hidden lg:flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={() => router.push("/")} className="h-12 w-12 rounded-2xl hover:bg-white hover:shadow-md transition-all">
              <ArrowLeft className="h-6 w-6" />
            </Button>
            <div>
              <h1 className="text-4xl font-black text-gray-900 tracking-tighter flex items-center gap-3">
                <TrendingUp className="h-10 w-10 text-indigo-600" />
                Sales Dashboard
              </h1>
              <p className="text-gray-500 font-medium">Daily performance and profit overview</p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 bg-white px-4 py-2 rounded-xl border shadow-sm">
              <Calendar className="h-4 w-4 text-gray-400" />
              <span className="text-sm font-bold text-gray-600">{new Date().toLocaleDateString()}</span>
            </div>
            <Button 
              className="bg-indigo-600 hover:bg-indigo-700 h-12 px-6 rounded-2xl gap-2 font-bold shadow-xl shadow-indigo-100 transition-all active:scale-95"
              onClick={generateReport}
              disabled={orders.length === 0}
            >
              <Printer className="h-5 w-5" />
              Generate Report
            </Button>
          </div>
        </div>

        {loading ? (
          <div className="h-96 flex items-center justify-center">
            <Loader2 className="h-12 w-12 animate-spin text-indigo-600 opacity-20" />
          </div>
        ) : (
          <>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 lg:gap-6">
              <Card className="border-none shadow-sm rounded-3xl bg-indigo-600 text-white overflow-hidden relative">
                <div className="absolute -right-4 -top-4 h-24 w-24 bg-white/10 rounded-full blur-2xl" />
                <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                  <CardTitle className="text-xs font-black uppercase tracking-widest opacity-80">Total Profit</CardTitle>
                  <TrendingUp className="h-4 w-4 opacity-80" />
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-black">₱{totalProfit.toLocaleString()}</div>
                  <p className="text-[10px] font-bold opacity-60 mt-1 uppercase tracking-wider">Net earnings today</p>
                </CardContent>
              </Card>

              <Card className="border-none shadow-sm rounded-3xl bg-white overflow-hidden">
                <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                  <CardTitle className="text-xs font-black uppercase tracking-widest text-gray-400">Total Sales</CardTitle>
                  <DollarSign className="h-4 w-4 text-indigo-600" />
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-black text-gray-900">₱{totalSales.toLocaleString()}</div>
                  <p className="text-[10px] font-bold text-indigo-600 mt-1 uppercase tracking-wider">Gross revenue</p>
                </CardContent>
              </Card>

              <Card className="border-none shadow-sm rounded-3xl bg-white overflow-hidden">
                <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                  <CardTitle className="text-xs font-black uppercase tracking-widest text-gray-400">Total Orders</CardTitle>
                  <ShoppingBag className="h-4 w-4 text-amber-500" />
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-black text-gray-900">{totalOrders}</div>
                  <p className="text-[10px] font-bold text-amber-500 mt-1 uppercase tracking-wider">Completed transactions</p>
                </CardContent>
              </Card>

              <Card className="border-none shadow-sm rounded-3xl bg-white overflow-hidden">
                <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                  <CardTitle className="text-xs font-black uppercase tracking-widest text-gray-400">System Status</CardTitle>
                  <UsersIcon className="h-4 w-4 text-emerald-500" />
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-black text-gray-900">🟢 Online</div>
                  <p className="text-[10px] font-bold text-emerald-500 mt-1 uppercase tracking-wider">System Active</p>
                </CardContent>
              </Card>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 lg:gap-8">
              <Card className="border-none shadow-sm rounded-3xl bg-white p-2">
                <CardHeader className="pb-2">
                  <CardTitle className="text-xl font-black tracking-tighter flex items-center gap-2">
                    <PieChart className="h-6 w-6 text-indigo-600" />
                    Category Performance
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-6 pt-4">
                    {Object.entries(categoryCount).sort((a, b) => b[1] - a[1]).map(([cat, count]) => (
                      <div key={cat} className="space-y-2">
                        <div className="flex justify-between text-sm">
                          <span className="font-black text-gray-700 uppercase text-[10px] tracking-widest">{cat}</span>
                          <span className="font-bold text-gray-400">{count} units</span>
                        </div>
                        <div className="w-full bg-gray-50 rounded-full h-3 overflow-hidden">
                          <div 
                            className="bg-indigo-600 h-full rounded-full transition-all duration-1000" 
                            style={{ width: `${(count / Object.values(categoryCount).reduce((a, b) => a + b, 0)) * 100}%` }}
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              <SimpleBackupManager />
            </div>
          </>
        )}
      </div>
    </div>
  );
}
